kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq
  namespace: sellers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: 192.168.100.12/sellers-utils/rabbitmq:latest
          ports:
            - name: management
              containerPort: 15672
              protocol: TCP
            - name: amq
              containerPort: 5672
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_PASS
              value: password
